# Generated by Django 5.2.7 on 2025-11-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mechanic_name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('feedback_text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
